version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    funlen:
      lines: 150
      statements: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - goconst
          - gocritic
          - lll
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
